apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.werf.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.werf.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.werf.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.werf.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        ports:
        - containerPort: 3000
        env:
        {{- range $name, $value := .Values.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - name: {{ $.Values.werf.name }}
          mountPath: /var/apps/{{ $.Values.werf.name }}
          subPath: var
        - name: {{ $.Values.werf.name }}
          mountPath: /etc/ssl/private
          subPath: certs
        - name: secret-volume
          readOnly: true
          subPath: ".env"
          mountPath: "/app/.env"
      volumes:
      - name: {{ $.Values.werf.name }}
        persistentVolumeClaim:
          claimName: {{ $.Values.werf.name }}-pvc
      - name: secret-volume
        secret:
          secretName: {{ $.Values.werf.name }}-secret
