apiVersion: v1
kind: Secret
metadata:
  name: cloudtreasury-secret
data:
  .env: |
        {{ if eq $.Values.werf.env "production" }}
        {{ werf_secret_file "env-production" | b64enc }}
        {{ end }}
        {{ if eq $.Values.werf.env "sandbox" }}
        {{ werf_secret_file "env-sandbox" | b64enc }}
        {{ end }}
