name: Pull request Deployment
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]
jobs:
  call-deployment:
    uses: ilb/iconicactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      setenv: env.DOMAIN=${{ github.head_ref || github.ref_name }}.${{ github.repository_owner }}.icncd.ru
