name: Testing Deployment
on:
  push:
    branches: ['master']
jobs:
  call-deployment:
    uses: ilb/iconicactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      setenv: env.DOMAIN=${{ github.head_ref || github.ref_name }}.${{ github.repository_owner }}.icncd.ru
